### ISSUE TITLE
Make progress animation loop infinitely

### ISSUE THREAD

**Issue by steelbrain** [atom/one-dark-ui#125]
It currently stops after a few seconds

**Comment by lee-dohm** [comment]
Can you please include some more information? Version of Atom? Version of the theme? Some repro steps perhaps?

**Comment by steelbrain** [comment]
Atom version 1.5.0
One Dark UI 0.51.0
Ubuntu GNOME 15.10

Repro
```
const progress = document.createElement('progress')
document.body.appendChild(progress)
```

Expected behavior:

 - The stripes in the progress element keep animating forever

Current behavior:

 - The animation stops after a few seconds

**Comment by simurai** [comment]
Sorry, this is intended behavior. The animation stops after [30 seconds](https://github.com/atom/one-dark-ui/commit/0be6a46f2e180830eeba3966a6fbd303046838d1).

The reason is that the animation could tax the CPU, see this [issue](https://github.com/atom/one-dark-ui/commit/0be6a46f2e180830eeba3966a6fbd303046838d1). It should be fine for a few seconds, but maybe not that ideal if it would animate forever. Like if a package forgets to remove the progress bar. Also, the thinking was that if something needs to buffer more than 30 seconds, something might be wrong anyways.

@steelbrain what's your use case for having it buffer for longer? If you want to show an animation but are not sure about the progress, you could also use a spinner instead: `<span class='loading loading-spinner-tiny inline-block'></span>`, that one animates forever.

If you really want the progress bar to animate longer than `30s`, you could override it in your package. Like:

```less
.my-package progress {
  -webkit-animation-iteration-count: infinite; // or a higher number, each count is 5s
}
```

just make sure to remove the progress element from the DOM if you don't need it.. or I think a `display: none` might already be ok too.

And maybe one day the animation could also be improved to be more performance friendly.

**Comment by steelbrain** [comment]
My use case is `atom-package-deps`, until a package is installed, "unknown progress" bar is shown, I was experiencing this in that bar, it stops spinning after a few seconds. I'm gonna override it in my package with the css you suggested.

Another interesting thing is that nobody sane would not remove that progress element from the DOM, I wonder why this limitation is in place, can you provide an example of when/how somebody showed a progress bar in DOM forever?

**Comment by simurai** [comment]
How long does it usually take "until a package is installed"? A few minutes? We can certainly increase how long it animates. Not sure about leaving it run forever.

Ya, most sane would remove it, but some might just hide it with `opacity` or the progress gets hidden by covering with something else. But then it still keeps repainting even though it's not visible.

Ok, maybe there is another approach. After some time, we could just slow down the animation. So maybe it would move once a second, like a slow frame-rate which hopefully is less CPU taxing, but you would still see that "something is going on".

**Comment by steelbrain** [comment]
Usually it takea about 2 minutes or less before a package is installed. I'd
be good with it if the limit was increased to that

**Comment by simurai** [comment]
The `progress` bar now buffers for 10min total.

- 1min (12runs) at normal speed,
- then slows down frame-rate for 9mins (108runs)

Hope that's a good compromise.

**Comment by steelbrain** [comment]
Thanks @simurai :+1:
