### ISSUE TITLE
Feature request: add setting to remove animations

### ISSUE THREAD

**Issue by j127** [atom/one-dark-ui#132]
This theme really looks great, but the animations and easing effects are _way_ too distracting. Can you add a checkbox to turn off all animations?

It's disorienting to have error messages pulsate needlessly before flying off the screen. They should just disappear without distracting the user. It's too much visual input when trying to solve bugs with add-ons.

If a user needs to see something, then a small amount of animation can bring attention to something, but when you're dismissing an error message, you're already done with it at that point and it should disappear inconspicuously.

Other than the animations, it's nearly perfect.

Thanks

**Comment by simurai** [comment]
Made a new issue https://github.com/atom/notifications/issues/123 about removing the animation when closing notifications. Since the animation doesn't come from this theme but rather from that package.

Something you could do to remove **all** animations and transitions. Add the following to your `styles.less` file:

```css
* {
  transition: none !important;
  animation: none !important;
}
```

it also works with the notifications, but it seems there is a delay that still keeps the notification visible for a while. So that would need to be changed in that package.

**Comment by j127** [comment]
Thanks - that fixed the most irritating part. I can live with the delay for now.

**Comment by simurai** [comment]
ok, I'll close this for now, but still good the remove the delay. It should also easy a bit this issue https://github.com/atom/notifications/issues/93.
