### ISSUE TITLE
pull-right and pull-left classes not working in SelectListView in 1.8 beta

### ISSUE THREAD

**Issue by akonwi** [atom/one-dark-ui#133]
This issue arose in my package repo at https://github.com/akonwi/git-plus/issues/445. The solution I've gone with is to use flexbox styling instead.

I created the issue here because so far it has only been reproduced with this theme. This could potentially be an issue in other places as well.

**Comment by simurai** [comment]
I think the "collapsing" happened because of https://github.com/atom/atom/pull/10782 + specifically for this theme, the [position: relative;](https://github.com/atom/one-dark-ui/pull/123/files#diff-516b27e7906b7be73aa90b1dee0acf78R11). Now the modals are flexible, but I guess broke your floating buttons.

Adding a `clearfix` class to the parent should've fixed it, but using Flexbox a great solution too. 👍

**Comment by akonwi** [comment]
Ok cool. I think I can close this then. For posterity, the solution is a `clearfix` class on the parent.

Thanks!
