### ISSUE TITLE
Default Layout Mode

### ISSUE THREAD

**Issue by whizkydee** [atom/one-dark-ui#149]
Hi guys,

The default **Layout Mode** for the one-dark-ui and probably all themes should be **Auto** and **Tab Sizing** should be **Even**. I've gone through a lot of trouble trying to get the tabs back to normal after the update without knowing that there is now a setting for the layout mode. And also, after the Atom update, the layout mode setting should be set to the previous choice of the user.

**Comment by simurai** [comment]
Sorry about changing the default for "tab sizing".

Because the Font Size and Layout Mode setting both have a default of `Auto`, it felt more consistent to also use it for Tab Sizing.

**Comment by benklebe** [comment]
I just had the same issue and my tabs used to be **Even** yet now they're **Auto** and it's setting them to **Minimum** when there's clearly enough space for them to be even. In fact I can't make the window large enough to get them to go back to **Even** when it's in **Auto** mode. I don't have a problem with the setting being **Auto** if it works correctly, but the **Auto** setting for tab size seems to be either buggy or otherwise not working as it should.

![screen shot 2016-07-08 at 12 52 30 pm](https://cloud.githubusercontent.com/assets/9062973/16694902/db195cfe-450a-11e6-8d2e-dc104e65b088.png)

**Comment by whizkydee** [comment]
@benbalter, @simurai Yeah. This should be reverted in the new Atom update. I doesn't appear cool at all.

**Comment by simurai** [comment]
> @benklebe and it's setting them to Minimum when there's clearly enough space for them to be even.

Unfortunately it's not _that_ smart. `Auto` switches based on window size. Currently it's set to `<= 1280x800`. Maybe we could lower that a bit, like `1000x600`, so that for example on a 13" MBP you would still get even tabs.

**Comment by 50Wliu** [comment]
Yeah, I think 13-inch laptops are a reasonable size to start setting "Even".
