### ISSUE TITLE
tab bar blue dot for changes made overlapping text of file name

### ISSUE THREAD

**Issue by masterkrang** [atom/one-dark-ui#153]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
yes
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
yes
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
yes
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
yes
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
yes
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
yes
For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The blue dot that symbolizes file changes that haven't been saved is overlapping the file name. This causes some very annoying problems:

- it's so easy to miss that I sometimes forget to save file changes
- makes it harder to read the file name

![image](https://cloud.githubusercontent.com/assets/452219/16897895/4a615ca8-4b76-11e6-9ee5-d7113052c26b.png)

### Steps to Reproduce

1. make a change to any file
2. try reading the text in the tab, you'll see a blue dot on top of the text

**Expected behavior:** Blue dot should have a margin so you can clearly see it and also be able to clearly read the file name.

**Actual behavior:** Blue dot is on top of the text, making it not obvious which files have changed, causing me to forget to save file changes.

### Versions
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

Mac OSX El Capitan

**Comment by albertosantini** [comment]
Settings / Themes / One Dark Ui / Tab Sizing: Even

```  
"one-dark-ui":
    tabSizing: "Even"
```

Hope that helps.

**Comment by simurai** [comment]
The overlapping will be fixed once Atom `1.10` is out:

 ![screen shot 2016-06-09 at 4 57 55 pm](https://cloud.githubusercontent.com/assets/378023/15922656/d79c7c72-2e63-11e6-8062-de7aec62fb2d.png)

But it just fades out the ending of the file name so that the blue dot isn't overlapping. Mostly the file extension. We could add extra margin, but the goal of the "minimal" Tab Sizing mode is to be as narrow as possible.

Alternatively, as @albertosantini mentioned, [switching](https://discuss.atom.io/t/the-tabs-got-shorter-in-v1-8-0-what-happened-how-do-i-go-back/29791) to the "Even" Tab Sizing mode, won't cut off file names as long as there aren't too many tabs.

**Comment by thomasjo** [comment]
This has been fixed, and as @simurai mentioned, will be part of the Atom v1.10 release.
