### ISSUE TITLE
Add option to switch tab close button to the left side

### ISSUE THREAD

**Issue by ooJerryLeeoo** [atom/one-dark-ui#202]
Like `Safari`.

![close-button-on-the-left-side](https://cloud.githubusercontent.com/assets/20783502/24997952/106d7688-206b-11e7-8554-3dd6d7700f20.png)

**Comment by simurai** [comment]
We were thinking about it: https://github.com/atom/one-dark-ui/pull/95

It got closed with: ...wait for `2.0` where "breaking" changes are more ok.

But that was a while ago and we might can reconsider since there aren't any plans for `2.0` yet.

**Comment by partydrone** [comment]
I was just reviewing the comments from #95—including mine. Since that time, I think I land squarely on the "native experience" side of the argument for this particular issue.

Considering the idea "muscle memory," I develop solely on a Mac, so I expect the close icon to be on the left side—that's where it is for everything else, and that's where my muscle memory takes me (when I use the mouse). Any app that doesn't do that (i.e., Chrome) calls attention to itself.

For "consistency across platforms," I think there's a certain amount of context to consider. No app exists entirely on its own. It lives in an environment created by the operating system it runs on. That operating system defines rules and sets expectations for its users. Apps that don't follow those rules or meet those expectations feel out-of-place.

Because of this, I think it's possible to draw a line between what should be consistent _across_ platforms and what should be consistent _to_ a platform. To that end, I humbly endorse an option to place the close button on the _left_ side, please. :pray: :smile:

But, if it doesn't make it in, I've lived with it this long because the beauty and aesthetic of the rest of the theme are more valuable to me than the location of the close tab button.

**Comment by simurai** [comment]
> I humbly endorse an option to place the close button on the left side, please. 🙏 😄

Ok, one can't say no to being asked that politely. :smile: There is now a PR #253 that should be available in Atom `1.27`.
