### ISSUE TITLE
Request: Dark theme with neutral white point

### ISSUE THREAD

**Issue by madig** [atom/one-dark-ui#239]
Currently, the dark theme has a bluish tint to it, while the white one has a warmer color. Given that many displays out there already have a colder white point than 6504K, I'd like to have the option to have a neutral white point for all colors (or  the default for the next iteration?). That would also help with making Atom not look a bit alien with terminals that use a neutral-ish gray as the background, like GNOME Terminal and others.

**Comment by simurai** [comment]
Thanks for the feedback. 🙇 

You could try to find a Syntax theme with more warmer colors. Like `atom-dark-syntax`. Then this UI theme automatically adapts to that background color.

![image](https://user-images.githubusercontent.com/378023/44465465-a6c41000-a658-11e8-8fc9-c4c845db0e3d.png)

Changing `one-dark-syntax` would need to wait for a next "iteration", otherwise people will ask to change it back.
