### ISSUE TITLE
Font sizing issues

### ISSUE THREAD

**Issue by aaronkavlie-wf** [atom/one-dark-ui#37]
Updated Atom from 0.189 to 0.190, and One Dark UI causes some font sizes to blow up.

Here's autocomplete-plus with go-plus:

![screen shot 2015-04-07 at 3 25 28 pm](https://cloud.githubusercontent.com/assets/7768348/7035122/8f1c7342-dd3a-11e4-87d5-ea4251696a66.png)

Here's the list of deprecated calls:

![screen shot 2015-04-07 at 3 27 46 pm](https://cloud.githubusercontent.com/assets/7768348/7035142/b0b782f8-dd3a-11e4-8e1c-b10edf76dd81.png)

**Comment by benogle** [comment]
I'm working on fixing ac+ right now. 

One major issue is that all the UI vars are ems rather than px like they used to be.

There are several other sizing issues as well:

![fnt-spacing](https://cloud.githubusercontent.com/assets/69169/7035290/e23a1baa-dd3b-11e4-9e43-6a8bfef233fd.jpg)

Padding too large on boxes:
![screen shot 2015-04-07 at 3 30 43 pm](https://cloud.githubusercontent.com/assets/69169/7035292/e3d98c70-dd3b-11e4-8b1c-61313f76b937.png)

**Comment by danqing** [comment]
![screen shot 2015-04-07 at 9 51 33 pm](https://cloud.githubusercontent.com/assets/5134133/7039102/69bdcbe6-dd71-11e4-8d4d-f62f7d467711.png)
Agreeing on huge margins. Is this intentional? I usually have a lot of files open, so the previous version really worked better for me.

**Comment by simurai** [comment]
Changed the `ui-variables` to use `px` units. This should be safer for other packages. Internally the One themes keep using `em` and you can still scale the UI from `styles.less`.

Also, reduced padding in find-and-replace and the modals.

**Comment by simurai** [comment]
@danqing The "margin" in the tabs is intentional. The text is now centered which makes it look like a margin. The space will be reduced if you have more tabs open. You can also left align them again by adding

```css
.tab-bar .tab .title {
  text-align: left;
}
```

to your `styles.less`. Although I think having them centered adds some space between the close icon and the next text label. And that makes it easier to tell them apart.
