### ISSUE TITLE
Background color defaulting with Solarized-Dark syntax theme

### ISSUE THREAD

**Issue by jsg2021** [atom/one-dark-ui#47]
Before the 0.190 update, One Dark UI with [Solarized Dark Syntax](https://atom.io/themes/solarized-dark-syntax) meshed well and the UI was a dark bluish color... now its more grey. 

See:
![screen shot 2015-04-09 at 11 00 04 am](https://cloud.githubusercontent.com/assets/577453/7071040/6bebf1c6-dea8-11e4-9255-aeccceaeb950.png)

**Comment by jsg2021** [comment]
Ok, it may not be defaulting, but it looks wrong... here's 0.5 for reference:
![screen shot 2015-04-10 at 11 48 00 am](https://cloud.githubusercontent.com/assets/577453/7092450/9fccdc88-df77-11e4-9f5b-95a9937fc8c1.png)

The Screenshot on the Readme for Sepia syntax looks closer to what I expected.

**Comment by simurai** [comment]
Yes, before it just got darkened a bit, but now there are 2 guards in place:

1. Limit saturation #22. Maybe that should only be done for text and not the background. Or only for "brownish" colors.. so it looks less like :hankey:. And you could argue that if you pick a very saturated syntax theme, you should be ok with having the UI saturated too.
2. In case the lightness is under `16%`, make the UI background lighter than the Syntax background. This was done so that there is still a noticeable difference, that got lost when too dark.

That's why Solarized dark is now desaturated and brighter. In case of Chester, these guards don't apply and thus looks more natural. I'll see if those "rules" can be tweaked a bit more.

**Comment by simurai** [comment]
The switch to lighter UI than editor happens now only below `10%` darkness. Solarized dark should look like this:

![screen shot 2015-05-27 at 12 16 39 am](https://cloud.githubusercontent.com/assets/378023/7830547/6ae56378-0489-11e5-98cd-4c0280740f14.png)

Closer to `0.5`, but without coloring the text.
