### ISSUE TITLE
Inactive tabs are hard to distinguish since "framed" update

### ISSUE THREAD

**Issue by brendanfalkowski** [atom/one-dark-ui#49]
Since the 0.6.3 "framed" update, inactive tabs no longer have a bounding box. I'm finding it very difficult to distinguish between tabs with many files open (reality). With a hard divider between tabs the padding could be decreased significantly. It's just not usable as-is. 

Along the same lines, a minimum tab width would be welcome with an overflow mechanism.

![screen shot 2015-04-10 at 2 31 08 pm](https://cloud.githubusercontent.com/assets/214924/7094333/57be2502-df8e-11e4-8ed9-690d1abe6bf7.png)

**Comment by simurai** [comment]
The larger gap is because now the close icon is next to the text label and not on top of it. That would need to be changed back again to allow less padding, even with a divider.

> Along the same lines, a minimum tab width would be welcome with an overflow mechanism.

I started to experiment on the `sm-tabs` branch. How do you like having the text labels never be truncated unless it exceeds the max width.

Before:

![screen shot 2015-04-13 at 12 12 08 am](https://cloud.githubusercontent.com/assets/378023/7106138/2536d6f6-e173-11e4-8b71-ea7046ceac2c.png)

After:

![screen shot 2015-04-13 at 12 12 40 am](https://cloud.githubusercontent.com/assets/378023/7106139/2bcfc39c-e173-11e4-8595-a7c2568e3e96.png)

So there are less tabs shown.. but
- you can actually read them
- there is no expanding when a tab is active. Resulting in no changing in positions which feels much calmer.
- The close button is always next to the text label. Making it easier to guess when hovering.

![tabs](https://cloud.githubusercontent.com/assets/378023/7106198/85602ff4-e174-11e4-98ca-4a2ba86a8cc0.gif)

ps. There is also an issue #13 about adding a "compact mode", which could be the same as pre `0.6.0`.

**Comment by brendanfalkowski** [comment]
1.1 — If the close icon padding is permanent, then I might always show the icon (not just for active tabs) so I can close tabs without switching to them. The spacing around the active tab is awkward in the before/after examples above. With the icon permanent it'd be tight feeling, but I think that wouldn't be an issue if inactive tabs had a dark 1px border delineating them.

1.2 — I think I prefer the close icon overlapping the content in the case when there are tons of tabs and names are being truncated. This leaves more room in the tab to read the title. Chrome does this well.

2.1 — It's definitely nicer not having the tabs change width on selection/deselection. A max-width for truncation would help.

2.2 — I wouldn't want all tabs over 20 chars being truncated though — only if there are too many tabs open. Otherwise that makes it harder to distinguish, ex: comparing the same files from two themes.

2.3 — Caveat: the issue with variable width tabs is closing them in quick succession jostles the close button's position. Again, I like how Chrome does this. When hovering the tab bar tabs don't resize, so you can click-click-click without moving the pointer to close multiple tabs. That only works if they're all the same width.

3.0 — Unrelated: highlight the active tab on the left side is brain-twitchy for me. It takes me a second to associate it to the right tab. I think I'd prefer that highlight be border-top, so it's a stronger visual signal and it anchors the size of the tab not the height of the tab bar. Especially if the tabs are variable width this would help register where the close icon will be quicker.

**Comment by philipgiuliani** [comment]
1.1 and 1.2: I totally agree with this, would be amazing @simurai if you could do that :) Would save a lot of space :)

2.3 https://github.com/atom/tabs/issues/129 I started experimenting with this, but my problem was that the active tab currently has another size than the other tabs :/ Would be great when they could have the same size, then we could implement the "delaying tab size" feature :)

**Comment by simurai** [comment]
Ok, I followed these points:

1.2 Close icon covers the text if it gets narrow.
2.1 Active tab stays the same width, so no shifting around.
2.2 Increased the max width a bit. Since the width has to stay the same, it can't just be wider only for tabs with long text labels.
2.3 All tabs have the same width. Should allow the "delaying tab size" feature for quick succession closing.

2.4 Also removed the ellipsis and instead the text just fades away. This lets you see an extra 2-3 characters.
2.5 Close icon is hidden also on the active tab and only shown on hover. Otherwise it would cover too much text. Making the active tab wider would conflict with some points above.
2.6 (half of 1.1) Added divider lines between inactive tabs. Making it easier to guess where the close icon is.

![tabs](https://cloud.githubusercontent.com/assets/378023/7152127/6250a932-e370-11e4-94e1-1c71ca9ef3c8.gif)

--------

3.0 Tried that out in the past. When there was no padding at the top, it clashed a bit with the bright title bar. With padding would work better. But it would make it a bit stronger since it stretches based on the tab width. Haven't changed it on the `sm-tabs` branch, but would look like this:

![screen shot 2015-04-15 at 1 11 31 pm](https://cloud.githubusercontent.com/assets/378023/7152182/62a0fefe-e371-11e4-9084-465dd6eb8cb6.png)

**Comment by jsg2021** [comment]
imho I've enjoyed the left highlight on the active tab.  personally, i don't like it as much on the top.

**Comment by philipgiuliani** [comment]
Great work @simurai seems a lot better than the current version :) I really like how the text of the tab is fading away.. Just amazing :boom: The border on the left is definitely better!

**Comment by philipgiuliani** [comment]
I just tried the branch out and it looks extremely good! Maybe the maximum tab size is a little bit to big? With a lot of tabs open its extremly clear now. And finally i see what the other tabs (Its more important to see the other tabs than the active tab, since i know where i currently am)

![bildschirmfoto 2015-04-15 um 09 18 28](https://cloud.githubusercontent.com/assets/5446019/7153855/685dc9c4-e350-11e4-90f5-6398be560016.png)

**Comment by simurai** [comment]
> Maybe the maximum tab size is a little bit to big?

Would be cool if the max width is larger but only if there is at least one large text label. That's probably what @brendanfalkowski meant in 2.2. Don't think it's possible with CSS alone and would need some JS to measure the length and change the max width.

**Comment by philipgiuliani** [comment]
Ok i understand! Lets leave it like this, its just amazing to work with this tabs now :)

**Comment by simurai** [comment]
Do you like that there is no close icon at all? I don't really miss it since I know it's there on hover, but could be controversial.

Also, personally I would increase the padding on the tabs a bit more. :innocent: Just to make it look less squeezed. Maybe there is no way around adding #40. People just have different priorities.

**Comment by philipgiuliani** [comment]
I don't see the close button as a problem.. Maybe we could show the close button on big tabs and hide it when they are smaller (again stolen from Chrome). But... Is that possible just with CSS?

**Comment by simurai** [comment]
Hmm.. the only way I can think of is having the close button relative as `inline-block` so that it wrapps (and is hidden) at some point.. then on hover position it `absolute`.

**Comment by brendanfalkowski** [comment]
Looking really good, the fixed tab widths and separators reduce the need for permanent close icons (for me). Agree that I'd much rather see more filename than the icon. Fade vs ellipsis was a good change to help that.

One man's opinion, but I really like the top highlight for active tabs (vs left side). Just more obvious that way.

For me, the case where max-width matters is opening two files with the same name, but from a different path. Because the path string starts from the tree root (and is appended not prepended) I always need the tooltip to distinguish them anyway (because they're deep paths) so it's not much of an issue.

![screen shot 2015-04-15 at 12 22 42 pm](https://cloud.githubusercontent.com/assets/214924/7163841/2b24dd8a-e36a-11e4-8c91-75c0f0de7bdb.png)

I'd be more interested in seeing a min-width for tabs though, and have the tab bar use `overflow-x:scroll` like Firefox. I can see that being disliked, but I think readable tabs is better than crunching to 3 chars.

![screen shot 2015-04-15 at 12 23 22 pm](https://cloud.githubusercontent.com/assets/214924/7163850/3dc700f8-e36a-11e4-9d2d-a70d18d21e86.png)

**Comment by simurai** [comment]
Made a PR #59 with the above.

> I'd be more interested in seeing a min-width for tabs though, and have the tab bar use overflow-x:scroll like Firefox.

There is overflow-x scrolling.

![tabs](https://cloud.githubusercontent.com/assets/378023/7432018/2032ddf8-f05f-11e4-8292-74cb341544bf.gif)

Actually should already work now. The min-width could be larger, but maybe that's something for `styles.less`.

There are also packages like https://atom.io/packages/tidy-tabs or https://atom.io/packages/zentabs that start closing old tabs so it never gets too crowded. Or https://atom.io/packages/sublime-tabs that only keeps a tab if you edit it.

**Comment by v3ss0n** [comment]
@simurai  this is already working in atom 198 ? How can i enable it? just ```overflow-x : scroll ```?

**Comment by philipgiuliani** [comment]
Its already enabled out-of-the-box. But you need a mouse which is able to scroll horizontally (mine is). Maybe we could translate the y mouse scroll to an x mouse scroll.

**Comment by v3ss0n** [comment]
i can scroll tabs with my mouse (Logitech : G602) in chrome , or do you mean something that have two scroll wheels?

**Comment by v3ss0n** [comment]
Oh i see , something that allow to scroll after click a scroll button? not mouse wheel?

**Comment by philipgiuliani** [comment]
No i mean something like this:
![oggsj](https://cloud.githubusercontent.com/assets/5446019/7565359/982fc432-f7ef-11e4-866c-a02fb0154255.png)

Currently its not possible. Maybe open an issue to request that feature. Would be interesting of course. I don't know if it should be theme-related or atom-tabs related.

**Comment by v3ss0n** [comment]
Thanks , now I can do it using Shift + Mouse wheel as advised by @izuzak  
https://github.com/atom/tabs/issues/137#issuecomment-100877401

I also advised to add "tab scroll" buttons at both ends of tab bar as advised here , may be you will interest in it. https://github.com/atom/tabs/issues/136

that way , possible to work with devices without mousewheels too.
