### ISSUE TITLE
Add tree-view focus indicator

### ISSUE THREAD

**Issue by mnquintana** [atom/one-dark-ui#52]
There's currently no way to visually tell if the tree-view is focused - it would be great if there was some kind of indication of whether or not the tree-view is focused.

(Also applies to one-light-ui, atom-dark-ui, and atom-light-ui but I'm too lazy to open issues in all of those repos at the moment)

**Comment by jerone** [comment]
:+1: for focus

A hover style for the tree-view would be great too.

**Comment by simurai** [comment]
Since the tabs have that little stripe on the left to indicate which pane is active.. we could use the same for the tree-view. But maybe harder to see, since it would touch the left edge of the window.

**Comment by mnquintana** [comment]
> Since the tabs have that little stripe on the left to indicate which pane is active.. we could use the same for the tree-view. But maybe harder to see, since it would touch the left edge of the window.

Where would the stripe go?

**Comment by simurai** [comment]
Left of the top root folder.

![stripe](https://cloud.githubusercontent.com/assets/378023/7578971/8d52eb0e-f897-11e4-8348-bff62e7f541c.png)

**Comment by mnquintana** [comment]
The only downside with that is that if the Tree View is scrolled then you still won't be able to tell if it has focus or not (without scrolling)

**Comment by simurai** [comment]
Ahh.. right. Might can be "anchored" to the top left corner.

**Comment by jsg2021** [comment]
fyi: if the tree is on the right side, focus indicator doesn't seem to be there at all.

**Comment by simurai** [comment]
Ok, added.

Had to put the marker on the right for the right side tree-view:

![screen shot 2015-05-16 at 6 11 37 pm](https://cloud.githubusercontent.com/assets/378023/7665549/4db2805a-fbf7-11e4-846a-a3ea74905e91.png)

Since it needs to be `position: fixed` and the tree-view can be resized.

**Comment by jerone** [comment]
I like it :clap:

**Comment by wbinnssmith** [comment]
Sorry to revive such an old issue, but I was going through inconsistencies throughout Atom and Atom IDE.

Maybe tree view (or one-dark's styling of it) can use the `@background-color-selected` rather than the custom tree version of the color? This is exactly what the GitHub package does:

The blue becomes grey when it the GitHub tab loses focus.

This way, it can provide a good amount of contrast when the user's using it and can double as an indicator by going grey when the tree loses focus.

We're thinking of implementing this pattern for Atom IDE Outline and Diagnostics. 

What do you think @simurai? Also no rush since you're on leave ;)

cc @shushz

**Comment by simurai** [comment]
@wbinnssmith Back!

👍  I like that suggestion, let's do it. 👉  #229
