### ISSUE TITLE
Fallback color for @ui-syntax-color doesn't work

### ISSUE THREAD

**Issue by asantos3** [atom/one-dark-ui#54]
When the variable syntax-background-color isn't used in a syntax theme [the fallback color for ui-syntax-color  doesn't work.](https://github.com/atom/one-dark-ui/blob/master/styles/ui-variables.less#L6)

I'm not using that variable in my theme because I'm using mixin guards to detect the base-background-color lightness to see if the theme is dark or light.

As a temporary work around this, I'm putting syntax-background-color to hsl(220,0.1%,20%) and changing the One Light UI tab colors but would like to not use it entirely and leave the background color to the theme.

**Comment by simurai** [comment]
That [fallback line](https://github.com/atom/one-dark-ui/blob/master/styles/ui-variables.less#L6) is a bit misleadig. Because it actually doesn't use the `hsl(220,24%,20%)` color. To make that mixin work, it just needs "some" color, but could be anything. That line only exists so it doesn't throw an error when a Syntax theme doesn't define the `@syntax-background-color` variable. The actual color that gets used is the fallback variable in [core](https://github.com/atom/atom/blob/master/static/variables/syntax-variables.less#L9). Not sure why, but it seems to somehow get prioritized. And because that variable is white (`#fff`), when you combine One dark plus your theme, the UI probably looks brown-ish.

It's an interesting use-case, because both themes (UI and Syntax) try to use the other theme's background color for themselves. Neither wants to go first and adapt to the other. So the core fallback variable has to step in and be the decision maker.

In my opinion, Syntax themes should take the lead and not worry about the UI. The reason behind that is:

1. The code is the most important thing in a code editor, it's where you look most of the time.
2. Therefore the background behind the code should go well with the syntax highlighting.
3. And lastly the UI should go well with the code background.

Does that make sense? You don't have to change your Syntax theme because lots of UI themes have a static background color, so it's still useful that it adapts to those. And in case of One dark it just turns brown because white (the core fallback) has a red hue.

**Comment by asantos3** [comment]
I think I should have been more specific of the actual problem, my theme actually works quite well without @syntax-background-color except for the tabs that stay white (as you can [see here](https://cloud.githubusercontent.com/assets/1958425/7221787/9072f6ce-e6f1-11e4-8114-ed75d8b3e5e9.png)).

Not all tabs are affected by it (e.g. Settings tab), aka [this line](https://github.com/atom/one-dark-ui/blob/master/styles/tabs.less#L53). I tracked it down to the fallback color not working but thinking about it better, shouldn't all tabs be styled equally?

I actually prioritize One Dark and Atom Dark though, I make sure it stays good on them above all.

**Comment by simurai** [comment]
>  shouldn't all tabs be styled equally?

The One dark UI theme tries to do that, but only if the Syntax theme is dark too. For light Syntax themes, it uses the (light) background color of that theme. It's to make the tab and editor appear connected and "seamless".. like this:

![screen shot 2015-04-21 at 6 23 31 pm](https://cloud.githubusercontent.com/assets/378023/7249187/955e1714-e853-11e4-8192-97d25fb4c5cd.png)

If the `@syntax-background-color` isn't defined, like in your case, then it uses the fallback color from core, which is white. And that's why the tab is white too. There might be a better way to avoid using the core variable as a fallback.

The Atom dark theme doesn't try to adapt to anything, so there is should be no problem.

**Comment by asantos3** [comment]
Thanks for the clarification, closing this then.
